PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {?offer schema:serialNumber ?id }
WHERE {
  ?offer rdf:type schema:Offer.
  ?offer schema:serialNumber ?id.
  FILTER REGEX(STR(?id), " ").
}
