DELETE {?uriOld ?p ?o}
INSERT {?uriNew ?p ?o}
WHERE {
  ?uriOld ?p ?o .
  FILTER REGEX(STR(?uriOld), "http://tourpack.redlink.io/seekda/2015/") .
  BIND (URI(REPLACE(STR(?uriOld),
        "http://tourpack.redlink.io/seekda/2015/",
        "http://sws16.tr1k.de:8080/businesses/")
    ) AS ?uriNew)
}
