PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

INSERT{
	?offer schema:BuyAction ?buyActionLink
}
where {
  ?hotel rdf:type schema:LodgingBusiness;
         schema:makesOffer ?offer;
         schema:branchCode ?bCode .
  ?offer schema:serialNumber ?serialNumber .
  BIND(IRI(CONCAT("http://localhost:8080/sws16/ServicePackaging/api/hotels/",?bCode,"/buy/", ?serialNumber)) AS ?buyActionLink)
}
